require("constants")

local StaticLayout = require("map/static_layout")
local Layouts=require("map/layouts").Layouts
Layouts["FADungeonStart"] = StaticLayout.Get("map/static_layouts/fa_dungeon_start")
Layouts["FAGoblinDungeonStart"] = StaticLayout.Get("map/static_layouts/fa_entrance")
Layouts["FAGoblinDungeonStart2"] = StaticLayout.Get("map/static_layouts/fa_secondlevelstartpoint")
Layouts["FAGoblinDungeonStart3"] = StaticLayout.Get("map/static_layouts/fa_thirdlevelstartpoint")
Layouts["FAGoblinRoom_1"] = StaticLayout.Get("map/static_layouts/fa_goblinroom_1")
Layouts["FA5x5GoblinRoom_1"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_1")
Layouts["FA5x5GoblinRoom_2"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_2")
Layouts["FA5x5GoblinRoom_3"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_3")
Layouts["FA5x5GoblinRoom_4"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_4")
Layouts["FA5x5GoblinRoom_5"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_5")
Layouts["FA5x5GoblinRoom_6"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_6")
Layouts["FA5x5GoblinRoom_7"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_7")
Layouts["FA5x5GoblinRoom_8"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_8")
Layouts["FA5x5GoblinRoom_9"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_9")
Layouts["FA5x5GoblinRoom_10"] = StaticLayout.Get("map/static_layouts/fa_5x5_goblinroom_10")
Layouts["FA10x10GoblinRoom_1"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_1")
Layouts["FA10x10GoblinRoom_2"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_2")
Layouts["FA10x10GoblinRoom_3"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_3")
Layouts["FA10x10GoblinRoom_4"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_4")
Layouts["FA10x10GoblinRoom_5"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_5")
Layouts["FA10x10GoblinRoom_6"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_6")
Layouts["FA10x10GoblinRoom_7"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_7")
Layouts["FA10x10GoblinRoom_8"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_8")
Layouts["FA10x10GoblinRoom_9"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_9")
Layouts["FA10x10GoblinRoom_10"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_10")
Layouts["FA10x10GoblinRoom_11"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_11")
Layouts["FA10x10GoblinRoom_12"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_12")
Layouts["FA10x10GoblinRoom_13"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_13")
Layouts["FA10x10GoblinRoom_14"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_14")
Layouts["FA10x10GoblinRoom_15"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_15")
Layouts["FA10x10GoblinRoom_16"] = StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_16")
Layouts["FA7x7GoblinRoom1_goblintrap_2"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_goblintrap_2")
Layouts["FA7x7GoblinRoom1_goblintrap_3"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_goblintrap_3")
Layouts["FA7x7GoblinRoom1_goblintrap_4"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_goblintrap_4")
Layouts["FA7x7GoblinRoom1_goblintrap_5"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_goblintrap_5")
Layouts["FA7x7GoblinRoom1_houndtrap_4"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_houndtrap_4")
Layouts["FA7x7GoblinRoom1_houndtrap_5"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_1_houndtrap_5")
Layouts["FA7x7GoblinRoom_2"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_2")
Layouts["FA7x7GoblinRoom_3"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_3")
Layouts["FA7x7GoblinRoom_4"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_4")
Layouts["FA7x7GoblinRoom_5"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_5")
Layouts["FA7x7GoblinRoom_6"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_6")
Layouts["FA7x7GoblinRoom_7"] = StaticLayout.Get("map/static_layouts/fa_7x7_goblinroom_7")
Layouts["FA25x25GoblinMaze_1"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_1")
Layouts["FA25x25GoblinMaze_2"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_2")
Layouts["FA25x25GoblinMaze_3"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_3")
Layouts["FAGoblinBossroom1"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_bossroom_roomA")
Layouts["FAGoblinBossroom2"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_bossroom_roomB")
Layouts["FAGoblinBossroom3"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_bossroom_roomC")


Layouts["FA9x9DefaultRoom"]=StaticLayout.Get("map/static_layouts/fa_9x9_goblinroom_Default")
Layouts["FA10x10DefaultRoom"]=StaticLayout.Get("map/static_layouts/fa_10x10_goblinroom_Default")
Layouts["FA25x25DefaultRoom"]=StaticLayout.Get("map/static_layouts/fa_25x25_goblinroom_Default")

Layouts["FAOrcSetEvil"]=StaticLayout.Get("map/static_layouts/orc_set_evilbiome")
Layouts["FAOrcSetHound"]=StaticLayout.Get("map/static_layouts/orc_set_houndbiome")
Layouts["FAOrcSetRocky"]=StaticLayout.Get("map/static_layouts/orc_set_rockybiome")

Layouts["FAcave_scrollchest_3"]=StaticLayout.Get("map/static_layouts/cave_scrollchest_3")
Layouts["FAcave_scrollchest_3_B"]=StaticLayout.Get("map/static_layouts/cave_scrollchest_3_B")
Layouts["FAevilbiome_scrollchest_2"]=StaticLayout.Get("map/static_layouts/evilbiome_scrollchest_2")
Layouts["FAflooring_scrollchest_1"]=StaticLayout.Get("map/static_layouts/flooring_scrollchest_1")
Layouts["FAflooring_scrollchest_1_B"]=StaticLayout.Get("map/static_layouts/flooring_scrollchest_1_B")
Layouts["FAgrass_scrollchest_1"]=StaticLayout.Get("map/static_layouts/grass_scrollchest_1")
Layouts["FAgrass_scrollchest_1_B"]=StaticLayout.Get("map/static_layouts/grass_scrollchest_1_B")
Layouts["FAgrass_scrollchest_1_C"]=StaticLayout.Get("map/static_layouts/grass_scrollchest_1_C")
Layouts["FArock_scrollchest_1"]=StaticLayout.Get("map/static_layouts/rock_scrollchest_1")
Layouts["FArock_scrollchest_B"]=StaticLayout.Get("map/static_layouts/rock_scrollchest_B")
Layouts["FArock_scrollchest_C"]=StaticLayout.Get("map/static_layouts/rock_scrollchest_C")

Layouts["FAMineExit"]=StaticLayout.Get("map/static_layouts/fa_mine_exit")
Layouts["FADorfTown1"]=StaticLayout.Get("map/static_layouts/dorf_town_1")
Layouts["FADorfTown1Graveyard"]=StaticLayout.Get("map/static_layouts/dorf_town_1_graveyard")
Layouts["FADorfTownField"]=StaticLayout.Get("map/static_layouts/dorf_town_field")
Layouts["FAOrcTown1"]=StaticLayout.Get("map/static_layouts/orc_town_1")

Layouts["FADorfFortressBase1"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_1_base")
Layouts["FADorfFortressStartRoom"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_1_A_entrance")
Layouts["FADorfFortressMerchants"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_B_merchants")
Layouts["FADorfFortressGrowRoom"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_D_growroom")
Layouts["FADorfFortressSmelting"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_F_smelting")
Layouts["FADorfFortressForge"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_G_forge")
Layouts["FADorfFortressBedrooms"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_e_bedrooms")
Layouts["FADorfFortressThrone"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_Throne")
Layouts["FADorfFortressStorage"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_I_storage")
Layouts["FADorfFortressAlcohol"]=StaticLayout.Get("map/static_layouts/20x20_dorf_fortress_lv_1_J_alcohol")

Layouts["FATestwithimpass"]=StaticLayout.Get("map/static_layouts/testwithimpass")
Layouts["FAOrcMineBasicsetTrap1"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_trap_1")
Layouts["FAOrcMineBasicsetTrap2"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_trap_2")
Layouts["FAOrcMineBasicsetTrap3"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_trap_3")
Layouts["FAOrcMineBasicsetTrap4"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_trap_4")
Layouts["FAOrcMineBasicsetTrap5"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_trap_5")

Layouts["FAOrcMineBasicset1"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_1")
Layouts["FAOrcMineBasicset2"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_2")
Layouts["FAOrcMineBasicset3"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_3")
Layouts["FAOrcMineBasicset4"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_4")
Layouts["FAOrcMineBasicset5"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_5")
Layouts["FAOrcMineBasicset6"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_6")
Layouts["FAOrcMineBasicset7"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_7")
Layouts["FAOrcMineBasicset8"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_8")
Layouts["FAOrcMineBasicset9"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_9")
Layouts["FAOrcMineBasicset10"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_10")
Layouts["FAOrcMineBasicset11"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_11")
Layouts["FAOrcMineBasicset12"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_12")
Layouts["FAOrcMineBasicset13"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_13")
Layouts["FAOrcMineBasicset14"]=StaticLayout.Get("map/static_layouts/orc_mine_basicset_14")

Layouts["FAOrcMineWortox"]=StaticLayout.Get("map/static_layouts/orc_mine_wortox_npc")