TUNING.ARMORGRASS = 220
TUNING.ARMORGRASS_ABSORPTION = .2
TUNING.ARMORWOOD = 450
TUNING.ARMORWOOD_ABSORPTION = .4
TUNING.ARMORMARBLE = 1050
TUNING.ARMORMARBLE_ABSORPTION = .60
TUNING.ARMORSNURTLESHELL_ABSORPTION = 0.8
TUNING.ARMORSNURTLESHELL = 1050
TUNING.ARMORMARBLE_SLOW = 0.7
TUNING.ARMORRUINS_ABSORPTION = 0.9
TUNING.ARMORRUINS = 1800
TUNING.ARMORSLURPER_ABSORPTION = 0.6
TUNING.ARMORSLURPER_SLOW_HUNGER = 0.6
TUNING.ARMORSLURPER = 300
TUNING.ARMOR_SANITY = 750
TUNING.ARMOR_SANITY_ABSORPTION = .8
TUNING.ARMOR_SANITY_DMG_AS_SANITY = 0.10

TUNING.STONEWALL_HEALTH=TUNING.STONEWALL_HEALTH*2
TUNING.WOODWALL_HEALTH=TUNING.WOODWALL_HEALTH*2
TUNING.HAYWALL_HEALTH=TUNING.HAYWALL_HEALTH*2
TUNING.RUINSWALL_HEALTH=TUNING.RUINSWALL_HEALTH*2

TUNING.GHOST_SPEED = 5
TUNING.GHOST_HEALTH = 300
TUNING.GHOST_DAMAGE=30

SANITY_DAY_LOSS=-100.0/(300*10)
PROTOTYPE_XP=50
SKELETONSPAWNDELAY=960
GHOST_MOUND_SPAWN_CHANCE=0.5
MOUND_RESET_PERIOD=20*480
FISHING_MERM_SPAWN_CHANCE=0.3

FA_DAMAGETYPE={
	POISON=1,
	FIRE=2,
	ACID=3,
	ELECTRIC=4,
	COLD=5,
	DEATH=6,
	HOLY=7,
	FORCE=8
}

FA_WETTNESS_DAMAGE_MODIFIER={
	[FA_DAMAGETYPE.COLD]=0.2,
	[FA_DAMAGETYPE.FIRE]=-0.4,
	[FA_DAMAGETYPE.ELECTRIC]=0.4
}

FA_QUAKER_LOOT_OVERRIDE ={}
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"] ={
	common = 
	{
		"rocks",
		"flint"
	},
	rare = 
	{
		"goldnugget",
		"nitre",
		"thulecite_pieces"
	},
	veryrare =
	{
		"redgem",
		"bluegem",
		"marble",
	},
}
FA_QUAKER_LOOT_OVERRIDE["ORC_MINES"]={
	common = 
	{"fa_lavapebble",},
	rare = 
	{
		"rocks",
		"fa_lavapebble",
	},
	veryrare =
	{
		"thulecite_pieces",
		"redgem",
		"marble",
	},
}
--just in case
FA_QUAKER_LOOT_OVERRIDE["ORC_FORTRESS"]=FA_QUAKER_LOOT_OVERRIDE["ORC_MINES"]
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_2"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_3"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_BOSSLEVEL"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])


FA_LEVEL_THREATS={}
FA_LEVEL_THREATS["GOBLIN_CAVE"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_2"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_3"]={"DUNGEON_GOBLINS"}

--this shouldnt be here
FA_LEVELS={}
