FA_DAMAGETYPE={
	POISON=1,
	FIRE=2,
	ACID=3,
	ELECTRIC=4,
	COLD=5,
	DEATH=6,
	HOLY=7,
	FORCE=8
}

--this shouldnt be here
FA_LEVELS={}
FA_LEVEL_THREATS={}

FA_LEVEL_THREATS["GOBLIN_CAVE"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_2"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_3"]={"DUNGEON_GOBLINS"}