FA_DAMAGETYPE={
	POISON=1,
	FIRE=2,
	ACID=3,
	ELECTRIC=4,
	COLD=5,
	DEATH=6,
	HOLY=7,
	FORCE=8
}

FA_WETTNESS_DAMAGE_MODIFIER={
	[FA_DAMAGETYPE.COLD]=0.2,
	[FA_DAMAGETYPE.FIRE]=-0.4,
	[FA_DAMAGETYPE.ELECTRIC]=0.4
}

FA_QUAKER_LOOT_OVERRIDE ={}
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"] ={
	common = 
	{
		"rocks",
		"flint"
	},
	rare = 
	{
		"goldnugget",
		"nitre",
		"thulecite_pieces"
	},
	veryrare =
	{
		"redgem",
		"bluegem",
		"marble",
	},
}
--just in case
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_2"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_3"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])
FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE_BOSSLEVEL"]=deepcopy(FA_QUAKER_LOOT_OVERRIDE["GOBLIN_CAVE"])


FA_LEVEL_THREATS={}
FA_LEVEL_THREATS["GOBLIN_CAVE"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_2"]={"DUNGEON_GOBLINS"}
FA_LEVEL_THREATS["GOBLIN_CAVE_3"]={"DUNGEON_GOBLINS"}

--this shouldnt be here
FA_LEVELS={}
