STRINGS.CHARACTER_TITLES.thief = "The Sneaky"
STRINGS.CHARACTER_NAMES.thief = "Pete"
STRINGS.CHARACTER_DESCRIPTIONS.thief = "* Stabby"
STRINGS.CHARACTER_QUOTES.thief = "\"Never saw me coming.\""
STRINGS.CHARACTERS.THIEF = {}

STRINGS.CHARACTER_TITLES.barb = "The Barbarian"
STRINGS.CHARACTER_NAMES.barb = "Brute strength and raw fury!"
STRINGS.CHARACTER_DESCRIPTIONS.barb = "1.  The Lower his life the stronger his attacks\n2.  Chops / mines 50% faster, is more hungry\n3.  Can eat raw meats with no neg effects\n5.  RAGE!"
STRINGS.CHARACTER_QUOTES.barb = "\"Don't get me angry!\""
STRINGS.CHARACTERS.BARB = {}

STRINGS.CHARACTER_TITLES.cleric = "The Cleric"
STRINGS.CHARACTER_NAMES.cleric = "cleric"
STRINGS.CHARACTER_DESCRIPTIONS.cleric = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.cleric = "\"I am a blank slate.\""
STRINGS.CHARACTERS.CLERIC = {}

STRINGS.CHARACTER_TITLES.druid = "The Druid"
STRINGS.CHARACTER_NAMES.druid = "Nature's protector"
STRINGS.CHARACTER_DESCRIPTIONS.druid = "1.  Animal companion\n2.  Druid spells\n3.  Loses sanity from destroying trees, grass and saplings\n4.  Loses sanity for killing innocents"
STRINGS.CHARACTER_QUOTES.druid = "\"When nature has work to be done, she creates a genius.\""
STRINGS.CHARACTERS.DRUID = {}

STRINGS.CHARACTER_TITLES.darkknight = "The Shadow"
STRINGS.CHARACTER_NAMES.darkknight = "darkknight"
STRINGS.CHARACTER_DESCRIPTIONS.darkknight = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.darkknight = "\"I am a blank slate.\""
STRINGS.CHARACTERS.DARKKNIGHT = {}

STRINGS.CHARACTER_TITLES.monk = "monk"
STRINGS.CHARACTER_NAMES.monk = "monk"
STRINGS.CHARACTER_DESCRIPTIONS.monk = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.monk = "\"I am a blank slate.\""
STRINGS.CHARACTERS.MONK = {}

STRINGS.CHARACTER_TITLES.necromancer = "necromancer"
STRINGS.CHARACTER_NAMES.necromancer = "necromancer"
STRINGS.CHARACTER_DESCRIPTIONS.necromancer = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.necromancer = "\"I am a blank slate.\""
STRINGS.CHARACTERS.NECROMANCER = {}

STRINGS.CHARACTER_TITLES.wizard = "wizard"
STRINGS.CHARACTER_NAMES.wizard = "wizard"
STRINGS.CHARACTER_DESCRIPTIONS.wizard = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.wizard = "\"I am a blank slate.\""
STRINGS.CHARACTERS.WIZARD = {}

STRINGS.CHARACTER_TITLES.tinkerer = "tinkerer"
STRINGS.CHARACTER_NAMES.tinkerer = "tinkerer"
STRINGS.CHARACTER_DESCRIPTIONS.tinkerer = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.tinkerer = "\"I am a blank slate.\""
STRINGS.CHARACTERS.TINKERER = {}

STRINGS.CHARACTER_TITLES.paladin = "The Paladin"
STRINGS.CHARACTER_NAMES.paladin = "The Paladin"
STRINGS.CHARACTER_DESCRIPTIONS.paladin = "1.  Starts with trusty holy sword\n2.  Can use sheilds\n3.  Battles evil\n4.  Divine Defender"
STRINGS.CHARACTER_QUOTES.paladin = "\"Nothing will stop the the righteous!\""
STRINGS.CHARACTERS.PALADIN = {}

STRINGS.CHARACTER_TITLES.ranger = "ranger"
STRINGS.CHARACTER_NAMES.ranger = "paladin"
STRINGS.CHARACTER_DESCRIPTIONS.ranger = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.ranger = "\"I am a blank slate.\""
STRINGS.CHARACTERS.RANGER = {}

STRINGS.CHARACTER_TITLES.bard = "bard"
STRINGS.CHARACTER_NAMES.bard = "bard"
STRINGS.CHARACTER_DESCRIPTIONS.bard = "* An example of how to create a mod character."
STRINGS.CHARACTER_QUOTES.bard = "\"I am a blank slate.\""
STRINGS.CHARACTERS.BARD = {}
-- You can also add any kind of custom dialogue that you would like. Don't forget to make
-- categores that don't exist yet using = {}
-- note: these are UPPER-CASE charcacter name

STRINGS.CHARACTERS.THIEF.DESCRIBE = {}
STRINGS.CHARACTERS.THIEF.DESCRIBE.EVERGREEN = "A template description of a tree."

STRINGS.NAMES.BOW = "Bow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOW = "Bow"
STRINGS.RECIPE_DESC.BOW = "Bow"
STRINGS.NAMES.ARROWS = "Arrows"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROWS = "Arrows"
STRINGS.RECIPE_DESC.ARROWS = "Arrows"
STRINGS.NAMES.WOODENSHIELD = "Wooden Shield"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODENSHIELD = "Wooden Shield"
STRINGS.RECIPE_DESC.WOODENSHIELD = "Wooden Shield"
STRINGS.NAMES.ROCKSHIELD = "Rock Shield"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCKSHIELD = "Rock Shield"
STRINGS.RECIPE_DESC.ROCKSHIELD = "Rock Shield"
STRINGS.NAMES.MARBLESHIELD = "Marble Shield"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MARBLESHIELD = "Marble Shield"
STRINGS.RECIPE_DESC.MARBLESHIELD = "Marble Shield"
STRINGS.NAMES.BONESHIELD = "Bone Shield"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BONESHIELD = "Bone Shield"
STRINGS.RECIPE_DESC.BONESHIELD = "Bone Shield"
STRINGS.NAMES.REFLECTSHIELD = "Reflection Shield"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.REFLECTSHIELD = "Reflection Shield"
STRINGS.NAMES.UNDEADBANESWORD = "Sword of Lesser Undead Bane"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.UNDEADBANESWORD = "Sword of Lesser Undead Bane"
STRINGS.NAMES.UNDEADBANESWORD2 = "Sword of Undead Bane"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.UNDEADBANESWORD2 = "Sword of Undead Bane"
STRINGS.NAMES.UNDEADBANESWORD3 = "Sword of Greater Undead Bane"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.UNDEADBANESWORD3 = "Sword of Greater Undead Bane"
STRINGS.NAMES.VORPALAXE = "Lesser Vorpal Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORPALAXE = "Lesser Vorpal Axe"
STRINGS.NAMES.VORPALAXE2 = "Vorpal Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORPALAXE2 = "Vorpal Axe"
STRINGS.NAMES.VORPALAXE3 = "Greater Vorpal Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORPALAXE3 = "Greater Vorpal Axe"
STRINGS.NAMES.FLAMINGSWORD = "Lesser Flaming Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMINGSWORD = "Lesser Flaming Sword"
STRINGS.NAMES.FLAMINGSWORD2 = "Flaming Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMINGSWORD2 = "Flaming Sword"
STRINGS.NAMES.FLAMINGSWORD3 = "Greater Flaming Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLAMINGSWORD3 = "Greater Flaming Sword"
STRINGS.NAMES.DAGGER = "Dagger of Lesser Slaying"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAGGER = "Dagger of Lesser Slaying"
STRINGS.NAMES.DAGGER2 = "Dagger of Slaying"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAGGER2 = "Dagger of Slaying"
STRINGS.NAMES.DAGGER3 = "Dagger of Greater Slaying"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAGGER3 = "Dagger of Greater Slaying"
STRINGS.NAMES.FROSTSWORD = "Lesser Frost Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROSTSWORD = "Lesser Frost Sword"
STRINGS.NAMES.FROSTSWORD2 = "Frost Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROSTSWORD2 = "Frost Sword"
STRINGS.NAMES.FROSTSWORD3 = "Greater Frost Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROSTSWORD3 = "Greater Frost Sword"
STRINGS.NAMES.ARMORFIRE = "Armor of Lesser Fire"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFIRE = "Armor of Lesser Fire"
STRINGS.NAMES.ARMORFIRE2 =  "Armor of Fire"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFIRE2 = "Armor of Fire"
STRINGS.NAMES.ARMORFIRE3 =  "Armor of Greater Fire"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFIRE3 = "Armor of Greater Fire"
STRINGS.NAMES.ARMORFROST = "Armor of Lesser Frost"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFROST = "Armor of Lesser Frost"
STRINGS.NAMES.ARMORFROST2 =  "Armor of Frost"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFROST2 = "Armor of Frost"
STRINGS.NAMES.ARMORFROST3 =  "Armor of Greater Frost"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORFROST3 = "Armor of Greater Frost"
STRINGS.NAMES.DKSWORD = "Evil Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DKSWORD = "Evil Sword"
STRINGS.NAMES.HOLYSWORD = "Holy Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLYSWORD = "Holy Sword"
STRINGS.NAMES.FA_LIGHTNINGSWORD = "Lesser Lightning Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LIGHTNINGSWORD = "Lesser Lightning Sword"
STRINGS.NAMES.FA_LIGHTNINGSWORD2 = "Lightning Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LIGHTNINGSWORD2 = "Lightning Sword"
STRINGS.NAMES.FA_LIGHTNINGSWORD3 = "Greater Lightning Sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LIGHTNINGSWORD3 = "Greater Lightning Sword"

STRINGS.NAMES.FA_FIREAXE = "Lesser Fire Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_FIREAXE = "Lesser Fire Axe"
STRINGS.NAMES.FA_FIREAXE2 = "Fire Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_FIREAXE2 =  "Fire Axe"
STRINGS.NAMES.FA_FIREAXE3 = "Greater Fire Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_FIREAXE3 = "Greater Fire Axe"
STRINGS.NAMES.FA_ICEAXE = "Lesser Ice Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_ICEAXE = "Lesser Ice Axe"
STRINGS.NAMES.FA_ICEAXE2 = "Ice Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_ICEAXE2 = "Ice Axe"
STRINGS.NAMES.FA_ICEAXE3 = "Greater Ice Axe"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_ICEAXE3 = "Greater Ice Axe"

STRINGS.NAMES.FA_WOODARROWS = "Wood Arrows"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_WOODARROWS =  "Wood Arrows"
STRINGS.NAMES.FA_ICEARROWS = "Ice Arrows"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_ICEARROWS = "Ice Arrows"
STRINGS.NAMES.FA_POISONARROWS = "Poison Arrows"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_POISONARROWS = "Poison Arrows"
STRINGS.NAMES.FA_FIREARROWS = "Fire Arrows"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_FIREARROWS = "Fire Arrows"


STRINGS.NAMES.FA_GOODBERRIES = "Goodberries"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_GOODBERRIES = "Goodberries"
STRINGS.NAMES.FA_BOTTLE_R = "Health Potion"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BOTTLE_R =  "Health Potion"
STRINGS.NAMES.FA_BOTTLE_Y = "Hunger Potion"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BOTTLE_Y ="Hunger Potion"
STRINGS.NAMES.FA_BOTTLE_G = "Sanity Potion"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BOTTLE_G = "Sanity Potion"
STRINGS.NAMES.FA_BOTTLE_B = "Wonder Potion"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BOTTLE_B = "Wonder Potion"
STRINGS.NAMES.HAT_GOBLINKING = "Goblin King Crown"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_GOBLINKING = "Goblin King Crown"
STRINGS.NAMES.HAT_POT = "Pot Hat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_POT = "Pot Hat"
STRINGS.NAMES.FA_LAVAROCK = "Lava rock"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LAVAROCK = "Lava rock"
STRINGS.NAMES.FA_LAVAPEBBLE = "Lava pebbles"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LAVAPEBBLE = "Lava pebbles"
STRINGS.NAMES.FA_LAVAWALL_ITEM = "Lava Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LAVAWALL_ITEM = "Lava Wall"
STRINGS.NAMES.FA_LAVAWALL = "Lava Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_LAVAWALL = "Lava Wall"

STRINGS.NAMES.FA_BLUETOTEM_ITEM = "Lightning Staff"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BLUETOTEM_ITEM = "Lightning Staff"
STRINGS.NAMES.FA_BLUETOTEM = "Lightning Staff"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BLUETOTEM = "Lightning Staff"
STRINGS.NAMES.FA_REDTOTEM_ITEM = "Fire Staff"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_REDTOTEM_ITEM = "Fire Staff"
STRINGS.NAMES.FA_REDTOTEM_KOS = "Fire Staff"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_REDTOTEM_KOS = "Fire Staff"
STRINGS.NAMES.FA_REDTOTEM = "Fire Staff"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_REDTOTEM = "Fire Staff"
STRINGS.NAMES.FA_ANIMATEDARMOR = "Armor"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_ANIMATEDARMOR = "Armor"
STRINGS.NAMES.FA_SKULL = "Skull"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_SKULL = "Skull"
STRINGS.NAMES.FA_BONFIRE = "Bonfire"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_BONFIRE = "Bonfire"

STRINGS.NAMES.POISONSPIDER = "Poison Spider"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONSPIDER =  "Poison Spider"
STRINGS.NAMES.POISONSPIDERDEN = "Poison Spider Den"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONSPIDERDEN =  "Poison Spider Den"
STRINGS.NAMES.POISONSPIDEREGGSACK = "Poison Spider Egg Sack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONSPIDEREGGSACK =  "Poison Spider Egg Sack"

STRINGS.NAMES.FA_DUNGEON_ENTRANCE = "Dungeon Entrance"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_DUNGEON_ENTRANCE = "Dungeon Entrance"
STRINGS.NAMES.FA_DUNGEON_EXIT = "Dungeon Exit"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_DUNGEON_EXIT = "Dungeon Exit"
STRINGS.NAMES.FA_SURFACE_PORTAL="Surface Portal"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_DUNGEON_EXIT ="Surface Portal"
STRINGS.NAMES.GOBLIN = "Goblin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLIN = "Goblin"
STRINGS.NAMES.GOBLINHUT = "Goblin Hut"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINHUT = "Goblin Hut"
STRINGS.NAMES.FAIRY_L20 = "Wolf"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FAIRY_L20 = "Wolf"
STRINGS.NAMES.DARKKNIGHTPET = "Shadow Pet"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DARKKNIGHTPET = "Shadow Pet"

STRINGS.NAMES.GOBLINKINGHEAD_ITEM = "Head of a goblin king"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINKINGHEAD_ITEM = "Head of a goblin king"
STRINGS.NAMES.GOBLINKINGHEAD = "Head of a goblin king"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINKINGHEAD = "Head of a goblin king"

STRINGS.NAMES.GOBLINSIGN_1 = "Goblin Sign Post"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINSIGN_1 = "It says 'Greenz noze's only'."
STRINGS.NAMES.GOBLINSIGN_2 = "Goblin Sign Post"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINSIGN_2 = "It says 'No heroz com herez, go away!'."
STRINGS.NAMES.GOBLINSIGN_3 = "Goblin Sign Post"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINSIGN_3 = "It says 'Danger!'."
STRINGS.NAMES.GOBLINSIGN_4 = "Goblin Sign Post"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINSIGN_4 = "It says 'Only prutty facez be herez'."
STRINGS.NAMES.GOBLINSIGN_5 = "Goblin Sign Post"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOBLINSIGN_5 = "It says 'Go bak now!'."

STRINGS.NAMES.FA_TELEPORTER="Teleporter"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_TELEPORTER="Teleporter"


STRINGS.NAMES.FA_DORF_BAG="Dwarven Bag of Holding"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_DORF_BAG="Dwarven Bag of Holding"
STRINGS.NAMES.FA_SCROLLCASE="Scroll case"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_SCROLLCASE="Scroll case"
STRINGS.NAMES.FA_WANDCASE="Wand Case"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_WANDCASE="Wand Case"
STRINGS.NAMES.FA_POTIONCASE="Potion Case"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_POTIONCASE="Potion Case"
STRINGS.NAMES.FA_FOODBAG="Food Bag"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FA_FOODBAG="Food Bag"

STRINGS.NAMES.MAGICMISSILEWAND = "Wand of Magic Missile"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGICMISSILEWAND = "Wand of Magic Missile"
STRINGS.RECIPE_DESC.MAGICMISSILEWAND = "Wand of Magic Missile"

STRINGS.NAMES.ACIDARROWWAND = "Wand of Acid Arrow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACIDARROWWAND = "Wand of Acid Arrow"
STRINGS.RECIPE_DESC.ACIDARROWWAND ="Wand of Acid Arrow"

STRINGS.NAMES.FIREBALLWAND = "Wand of Fireball"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIREBALLWAND = "Wand of Fireball"
STRINGS.RECIPE_DESC.FIREBALLWAND =  "Wand of Fireball"

STRINGS.NAMES.ICESTORMWAND = "Wand of IceStorm"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICESTORMWAND = "Wand of IceStorm"
STRINGS.RECIPE_DESC.ICESTORMWAND =  "Wand of IceStorm"

STRINGS.NAMES.FIREWALLWAND = "Wand of FireWall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIREWALLWAND = "Wand of FireWall"
STRINGS.RECIPE_DESC.FIREWALLWAND =  "Wand of FireWall"

STRINGS.NAMES.FIREWALLWAND_INSTA = "Wand of FireWall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIREWALLWAND_INSTA = "Wand of FireWall"
STRINGS.RECIPE_DESC.FIREWALLWAND_INSTA =  "Wand of FireWall"

STRINGS.NAMES.SUNBURSTWAND = "Wand of Sunburst"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUNBURSTWAND ="Wand of Sunburst"
STRINGS.RECIPE_DESC.SUNBURSTWAND ="Wand of Sunburst"

STRINGS.NAMES.SPELL_INVISIBILITY = "Invisibility"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_INVISIBILITY =  "Invisibility"
STRINGS.RECIPE_DESC.SPELL_INVISIBILITY = "Invisibility"

STRINGS.NAMES.SPELL_HASTE = "Haste"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_HASTE =  "Haste"
STRINGS.RECIPE_DESC.SPELL_HASTE = "Haste"

STRINGS.NAMES.SPELL_SUMMONFEAST = "Summon feast"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_SUMMONFEAST =  "Summon feast"
STRINGS.RECIPE_DESC.SPELL_SUMMONFEAST =  "Summon feast"

STRINGS.NAMES.PRISMATICWAND = "Prismatic Wall"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRISMATICWAND =  "Prismatic Wall"
STRINGS.RECIPE_DESC.PRISMATICWAND = "Prismatic Wall"

STRINGS.NAMES.LIGHTNINGBOLTWAND = "Wand of Lightning Bolt"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTNINGBOLTWAND =  "Wand of Lightning Bolt"
STRINGS.RECIPE_DESC.LIGHTNINGBOLTWAND = "Wand of Lightning Bolt"

STRINGS.NAMES.TRAP_CIRCLEOFDEATH = "Circle of Death"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAP_CIRCLEOFDEATH = "Circle of Death"
STRINGS.RECIPE_DESC.TRAP_CIRCLEOFDEATH = "Circle of Death"

STRINGS.CHARACTERS.GENERIC.FA_FEAR_DEADKING="My King is DEAD!"

--[[
STRINGS.CHARACTERS.GENERIC.FA_WONDER_SPEEDBOOST
STRINGS.CHARACTERS.GENERIC.FA_WONDER_SPEEDNERF
STRINGS.CHARACTERS.GENERIC.FA_WONDER_HPRESTORE
STRINGS.CHARACTERS.GENERIC.FA_WONDER_HPDAMAGE
STRINGS.CHARACTERS.GENERIC.FA_WONDER_POISON
STRINGS.CHARACTERS.GENERIC.FA_WONDER_SLEEP
STRINGS.CHARACTERS.GENERIC.FA_WONDER_GOLD
STRINGS.CHARACTERS.GENERIC.FA_WONDER_LS
STRINGS.CHARACTERS.GENERIC.FA_WONDER_SANITYRESTORE
STRINGS.CHARACTERS.GENERIC.FA_WONDER_INSANITY
STRINGS.CHARACTERS.GENERIC.FA_WONDER_HUNGERRESTORE
STRINGS.CHARACTERS.GENERIC.FA_WONDER_TELEPORT
STRINGS.CHARACTERS.GENERIC.FA_WONDER_NIGHTMAREFUEL
STRINGS.CHARACTERS.GENERIC.FA_WONDER_NAUGHTINESS
STRINGS.CHARACTERS.GENERIC.FA_WONDER_ITEMDAMAGE
STRINGS.CHARACTERS.GENERIC.FA_WONDER_ITEMREPAIR
STRINGS.CHARACTERS.GENERIC.FA_WONDER_BLUEPRINT
STRINGS.CHARACTERS.GENERIC.FA_WONDER_GEMS
STRINGS.CHARACTERS.GENERIC.FA_WONDER_HOUNDED
]]


STRINGS.CHARACTERS.PALADIN.FA_WONDER_SPEEDBOOST="I have been blessed with speed!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_SPEEDNERF="I have been cursed with a slow spell!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_HPRESTORE="I have been restored!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_HPDAMAGE="That does not feel good."
STRINGS.CHARACTERS.PALADIN.FA_WONDER_POISON="I do not feel well."
STRINGS.CHARACTERS.PALADIN.FA_WONDER_SLEEP="I feel...."
STRINGS.CHARACTERS.PALADIN.FA_WONDER_GOLD="My god has blessed me with wealth!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_LS="My god, what have I done?"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_SANITYRESTORE="I am truly enlightened."
STRINGS.CHARACTERS.PALADIN.FA_WONDER_INSANITY="Something has corrupted my beliefs!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_HUNGERRESTORE="My god has provided me with a bounty of food."
STRINGS.CHARACTERS.PALADIN.FA_WONDER_TELEPORT="This is the most evil of magic!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_NIGHTMAREFUEL="These things are most foul!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_NAUGHTINESS="I must do penance!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_ITEMDAMAGE="My items have been cursed!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_ITEMREPAIR="I feel my items have been blessed!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_BLUEPRINT="No one can design things better than my god!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_GEMS="My god can create the most beautiful of things!"
STRINGS.CHARACTERS.PALADIN.FA_WONDER_HOUNDED="My god warns me, something is coming..."

STRINGS.CHARACTERS.DRUID.FA_WONDER_SPEEDBOOST="I feel as fast as the wind!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_SPEEDNERF="I feel as slow as a stream in winter."
STRINGS.CHARACTERS.DRUID.FA_WONDER_HPRESTORE="I feel more healthy"
STRINGS.CHARACTERS.DRUID.FA_WONDER_HPDAMAGE="Ouch!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_POISON="This is unnatural!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_SLEEP="Night is coming early..."
STRINGS.CHARACTERS.DRUID.FA_WONDER_GOLD="Nature has truly blessed me!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_LS="Oh Mother, why have you forsaken me..."
STRINGS.CHARACTERS.DRUID.FA_WONDER_SANITYRESTORE="I feel as clear as a still pond"
STRINGS.CHARACTERS.DRUID.FA_WONDER_INSANITY="Oh this is not natural!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_HUNGERRESTORE="Nature has given me a bounty!"
STRINGS.CHARACTERS.DRUID.FA_WONDER_TELEPORT="The winds have blown me off course"
STRINGS.CHARACTERS.DRUID.FA_WONDER_NIGHTMAREFUEL="These are not natural"
STRINGS.CHARACTERS.DRUID.FA_WONDER_NAUGHTINESS="What have I done?"
STRINGS.CHARACTERS.DRUID.FA_WONDER_ITEMDAMAGE="Nature has broken my gear"
STRINGS.CHARACTERS.DRUID.FA_WONDER_ITEMREPAIR="Nature has blessed my gear"
STRINGS.CHARACTERS.DRUID.FA_WONDER_BLUEPRINT="Nature has better designs"
STRINGS.CHARACTERS.DRUID.FA_WONDER_GEMS="Mother has given me a wondrous gift"
STRINGS.CHARACTERS.DRUID.FA_WONDER_HOUNDED="I smell something on the wind."

STRINGS.CHARACTERS.BARB.FA_WONDER_SPEEDBOOST="Me fast!"
STRINGS.CHARACTERS.BARB.FA_WONDER_SPEEDNERF="Me slow!"
STRINGS.CHARACTERS.BARB.FA_WONDER_HPRESTORE="Yar!!!"
STRINGS.CHARACTERS.BARB.FA_WONDER_HPDAMAGE="Grr..."
STRINGS.CHARACTERS.BARB.FA_WONDER_POISON="Me no feel so good."
STRINGS.CHARACTERS.BARB.FA_WONDER_SLEEP="Me no......."
STRINGS.CHARACTERS.BARB.FA_WONDER_GOLD="Nice and shiny!"
STRINGS.CHARACTERS.BARB.FA_WONDER_LS="Grrr... bright light hurts"
STRINGS.CHARACTERS.BARB.FA_WONDER_SANITYRESTORE="Mmmmmm"
STRINGS.CHARACTERS.BARB.FA_WONDER_INSANITY="Kill, must kill!"
STRINGS.CHARACTERS.BARB.FA_WONDER_HUNGERRESTORE="Yum, Yum."
STRINGS.CHARACTERS.BARB.FA_WONDER_TELEPORT="Where me going..."
STRINGS.CHARACTERS.BARB.FA_WONDER_NIGHTMAREFUEL="What this?"
STRINGS.CHARACTERS.BARB.FA_WONDER_NAUGHTINESS="Me be bad."
STRINGS.CHARACTERS.BARB.FA_WONDER_ITEMDAMAGE="Why my stuffs break!"
STRINGS.CHARACTERS.BARB.FA_WONDER_ITEMREPAIR="My stuffs got fixed!"
STRINGS.CHARACTERS.BARB.FA_WONDER_BLUEPRINT="Hmm... paper to make stuff."
STRINGS.CHARACTERS.BARB.FA_WONDER_GEMS="Shiny!"
STRINGS.CHARACTERS.BARB.FA_WONDER_HOUNDED="Something coming?"

STRINGS.ACTIONS.RELOAD="Reload"

STRINGS.UI.WORLDGEN.GOBLIN={}
STRINGS.UI.WORLDGEN.GOBLIN.VERBS={"Wrangling","Generating","Herding","Embiggening","Iterating upon","Insinuating","Reticulating","Inserting","Framing"}
STRINGS.UI.WORLDGEN.GOBLIN.NOUNS={"Pot Helms","GOBLINS!","Poop","Walls","Monsters","a keen sense of despair","Goblin huts","Treasure and other loots","Goblin plans for world domination!","The Kings stronghold"}

STRINGS.NAMES.SPELL_DIVINEMIGHT = "Divine Might"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_DIVINEMIGHT = "Divine Might"
STRINGS.RECIPE_DESC.SPELL_DIVINEMIGHT = "Divine Might"

STRINGS.NAMES.SPELL_CALLDIETY = "Call Diety"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_CALLDIETY = "Call Diety"
STRINGS.RECIPE_DESC.SPELL_CALLDIETY = "Call Diety"

STRINGS.NAMES.SPELL_LIGHT = "Banish Darkness"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_LIGHT = "Banish Darkness"
STRINGS.RECIPE_DESC.SPELL_LIGHT = "Banish Darkness"

STRINGS.NAMES.SPELL_HEAL = "Heal"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_HEAL = "Heal"
STRINGS.RECIPE_DESC.SPELL_HEAL = "Heal"

STRINGS.NAMES.SPELL_BLADEBARRIER = "Blade Barrier"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_BLADEBARRIER = "Blade Barrier"
STRINGS.RECIPE_DESC.SPELL_BLADEBARRIER = "Blade Barrier"

STRINGS.NAMES.SPELL_SUMMONFEAST = "Summon feast"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_SUMMONFEAST =  "Summon feast"
STRINGS.RECIPE_DESC.SPELL_SUMMONFEAST =  "Summon feast"

STRINGS.NAMES.SPELL_LIGHTNING = "Call Lightning"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_LIGHTNING = "Call Lightning"
STRINGS.RECIPE_DESC.SPELL_LIGHTNING = "Call Lightning"

STRINGS.NAMES.SPELL_EARTHQUAKE = "Earthquake"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_EARTHQUAKE = "Earthquake"
STRINGS.RECIPE_DESC.SPELL_EARTHQUAKE = "Earthquake"

STRINGS.NAMES.SPELL_GROW = "Grow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_GROW = "Grow"
STRINGS.RECIPE_DESC.SPELL_GROW = "Grow"

STRINGS.NAMES.SPELL_GUARDIAN = "Summon Tree Guardian"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_GUARDIAN = "Summon Tree Guardian"
STRINGS.RECIPE_DESC.SPELL_GUARDIAN = "Summon Tree Guardian"

STRINGS.NAMES.SPELL_SUMMONGOODBERRIES = "Summon Goodberries"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_SUMMONGOODBERRIES = "Summon Goodberries"
STRINGS.RECIPE_DESC.SPELL_SUMMONGOODBERRIES = "Summon Goodberries"

STRINGS.NAMES.SPELL_WAIL = "Wail of Banishee"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_WAIL =  "Wail of Banishee"
STRINGS.RECIPE_DESC.SPELL_WAIL =  "Wail of Banishee"

STRINGS.NAMES.SPELL_SUMMON_SWARM = "Summon Swarm"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_SUMMON_SWARM = "Summon Swarm"
STRINGS.RECIPE_DESC.SPELL_SUMMON_SWARM =  "Summon Swarm"

STRINGS.NAMES.SPELL_SUMMON_WRAITH = "Summon Wraith"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPELL_SUMMON_WRAITH =  "Summon Wraith"
STRINGS.RECIPE_DESC.SPELL_SUMMON_WRAITH =  "Summon Wraith"

